name: finanacial-data-management-app

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 5001:5001
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    ports:
      - 5173:5173
    depends_on:
      - api
    

